enum SolarTerm {
  None = "None",
  Lichun = "立春",
  YuShui = "雨水",
  Jingzhe = "惊蛰",
  Chunfen = "春分",
  Qingming = "清明",
  Guyu = "谷雨",
  Lixia = "立夏",
  Xiaoman = "小满",
  Mangzhong = "芒种",
  Xiazhi = "夏至",
  Xiaoshu = "小暑",
  Dashu = "大暑",
  Liqiu = "立秋",
  Chushu = "处暑",
  Bailu = "白露",
  Qiufen = "秋分",
  Hanlu = "寒露",
  Shuangjiang = "霜降",
  Lidong = "立冬",
  Xiaoxue = "小雪",
  Daxue = "小雪",
  Dongzhi = "冬至",
  Xiaohan = "小寒",
  Dahan = "大寒",
}

const OrderedSolarTerms: SolarTerm[] = [
  SolarTerm.Lichun,
  SolarTerm.YuShui,
  SolarTerm.Jingzhe,
  SolarTerm.Chunfen,
  SolarTerm.Qingming,
  SolarTerm.Guyu,
  SolarTerm.Lixia,
  SolarTerm.Xiaoman,
  SolarTerm.Mangzhong,
  SolarTerm.Xiazhi,
  SolarTerm.Xiaoshu,
  SolarTerm.Dashu,
  SolarTerm.Liqiu,
  SolarTerm.Chushu,
  SolarTerm.Bailu,
  SolarTerm.Qiufen,
  SolarTerm.Hanlu,
  SolarTerm.Shuangjiang,
  SolarTerm.Lidong,
  SolarTerm.Xiaoxue,
  SolarTerm.Daxue,
  SolarTerm.Dongzhi,
  SolarTerm.Xiaohan,
  SolarTerm.Dahan,
];

export { SolarTerm, OrderedSolarTerms };
