enum SolarTerm {
  None = "None",
  Lichun = "立春",
  YuShui = "雨水",
  Jingzhe = "惊蛰",
  Chunfen = "春分",
  Qingming = "清明",
  Guyu = "谷雨",
  Lixia = "立夏",
  Xiaoman = "小满",
  Mangzhong = "芒种",
  Xiazhi = "夏至",
  Xiaoshu = "小暑",
  Dashu = "大暑",
  Liqiu = "立秋",
  Chushu = "处暑",
  Bailu = "白露",
  Qiufen = "秋分",
  Hanlu = "寒露",
  Shuangjiang = "霜降",
  Lidong = "立冬",
  Xiaoxue = "小雪",
  Daxue = "小雪",
  Dongzhi = "冬至",
  Xiaohan = "小寒",
  Dahan = "大寒",
}

const OrderedSolarTerms: SolarTerm[] = [
  SolarTerm.Lichun,
  SolarTerm.YuShui,
  SolarTerm.Jingzhe,
  SolarTerm.Chunfen,
  SolarTerm.Qingming,
  SolarTerm.Guyu,
  SolarTerm.Lixia,
  SolarTerm.Xiaoman,
  SolarTerm.Mangzhong,
  SolarTerm.Xiazhi,
  SolarTerm.Xiaoshu,
  SolarTerm.Dashu,
  SolarTerm.Liqiu,
  SolarTerm.Chushu,
  SolarTerm.Bailu,
  SolarTerm.Qiufen,
  SolarTerm.Hanlu,
  SolarTerm.Shuangjiang,
  SolarTerm.Lidong,
  SolarTerm.Xiaoxue,
  SolarTerm.Daxue,
  SolarTerm.Dongzhi,
  SolarTerm.Xiaohan,
  SolarTerm.Dahan,
];

// enum SolarTermEnglish {
//   BeginningOfSpring = "Beginning of Spring",
//   RainWater = "Rain Water",
//   AwakeningOfInsects = "Awakening of Insects",
//   SpringEquinox = "Spring Equinox",
//   PureBrightness = "Pure Brightness",
//   GrainRain = "Grain Rain",
//   BeginningOfSummer = "Beginning of Summer",
//   GrainBuds = "Grain Buds",
//   GrainInEar = "Grain in Ear",
//   SummerSolstice = "Summer Solstice",
//   MinorHeat = "Minor Heat",
//   MajorHeat = "Major Heat",
//   BeginningOfAutumn = "Beginning of Autumn",
//   EndOfHeat = "End of Heat",
//   WhiteDew = "White Dew",
//   AutumnalEquinox = "Autumnal Equinox",
//   ColdDew = "Cold Dew",
//   FrostDescent = "Frost Descent",
//   BeginningOfWinter = "Beginning of Winter",
//   MinorSnow = "Minor Snow",
//   MajorSnow = "Major Snow",
//   WinterSolstice = "Winter Solstice",
//   MinorCold = "Minor Cold",
//   MajorCold = "Major Cold",
// }
// const OrderedSolarTermsEnglish: SolarTermEnglish[] = [
//   SolarTermEnglish.BeginningOfSpring,
//   SolarTermEnglish.RainWater,
//   SolarTermEnglish.AwakeningOfInsects,
//   SolarTermEnglish.SpringEquinox,
//   SolarTermEnglish.PureBrightness,
//   SolarTermEnglish.GrainRain,
//   SolarTermEnglish.BeginningOfSummer,
//   SolarTermEnglish.GrainBuds,
//   SolarTermEnglish.GrainInEar,
//   SolarTermEnglish.SummerSolstice,
//   SolarTermEnglish.MinorHeat,
//   SolarTermEnglish.MajorHeat,
//   SolarTermEnglish.BeginningOfAutumn,
//   SolarTermEnglish.EndOfHeat,
//   SolarTermEnglish.WhiteDew,
//   SolarTermEnglish.AutumnalEquinox,
//   SolarTermEnglish.ColdDew,
//   SolarTermEnglish.FrostDescent,
//   SolarTermEnglish.BeginningOfWinter,
//   SolarTermEnglish.MinorSnow,
//   SolarTermEnglish.MajorSnow,
//   SolarTermEnglish.WinterSolstice,
//   SolarTermEnglish.MinorCold,
//   SolarTermEnglish.MajorCold,
// ];

export {
  SolarTerm,
  OrderedSolarTerms,
  // SolarTermEnglish,
  // OrderedSolarTermsEnglish,
};
